package commands

import (
	"fmt"
	"sort"
	"strings"

	"github.com/napalu/goopt/v2"
	"github.com/napalu/goopt/v2/completion"
	"github.com/napalu/sympa/internal/options"
)

// Commands whose positional args are secret names.
var secretCommands = map[string]bool{
	"show": true, "edit": true, "rm": true, "totp": true,
	"insert": true, "generate": true, "mv": true, "cp": true,
}

// Commands whose positional args are folder names.
var folderCommands = map[string]bool{
	"ls": true,
}

// cmdFlag represents a flag resolved for a specific command.
type cmdFlag struct {
	Long  string
	Short string
	Desc  string
	Type  completion.FlagType
}

func handleCompletion(p *goopt.Parser, _ *goopt.Command) error {
	cfg, ok := goopt.GetStructCtxAs[*options.Config](p)
	if !ok {
		return errNoConfig
	}

	data := p.GetCompletionData()
	prog := "sympa"

	var script string
	switch cfg.Completion.Shell {
	case "bash":
		script = generateBash(prog, data)
	case "zsh":
		script = generateZsh(prog, data)
	case "fish":
		script = generateFish(prog, data)
	default:
		return fmt.Errorf("unsupported shell: %q (supported: bash, zsh, fish)", cfg.Completion.Shell)
	}

	fmt.Print(script)
	return nil
}

// categorizeCommands splits command paths into top-level commands and
// a map of parent → []subcommand names.
func categorizeCommands(commands []string) (topLevel []string, subCmds map[string][]string) {
	subCmds = make(map[string][]string)
	seen := make(map[string]bool)
	for _, cmd := range commands {
		parts := strings.SplitN(cmd, " ", 2)
		if len(parts) == 1 {
			if !seen[cmd] {
				topLevel = append(topLevel, cmd)
				seen[cmd] = true
			}
		} else {
			parent := parts[0]
			sub := parts[1]
			subCmds[parent] = append(subCmds[parent], sub)
			if !seen[parent] {
				topLevel = append(topLevel, parent)
				seen[parent] = true
			}
		}
	}
	return
}

// flagsForCommand extracts flags for a specific command from CompletionData.
func flagsForCommand(cmd string, data completion.CompletionData) []cmdFlag {
	var result []cmdFlag
	for _, entry := range data.CommandFlags[cmd] {
		result = append(result, cmdFlag{
			Long:  entry.Long,
			Short: entry.Short,
			Desc:  entry.Description,
			Type:  entry.Type,
		})
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Long < result[j].Long })
	return result
}

// isStandalone returns true if the flag is boolean/standalone (no value).
func isStandalone(t completion.FlagType) bool {
	return t == completion.FlagTypeStandalone
}

// flagValueDescriptions returns the Description fields from FlagValues for a
// given flag (looked up by long name). cmd is the command scope ("" for global).
func flagValueDescriptions(cmd, long string, fv map[string][]completion.CompletionValue) []string {
	key := long
	if cmd != "" {
		key = cmd + "@" + long
	}
	vals := fv[key]
	if len(vals) == 0 {
		return nil
	}
	out := make([]string, len(vals))
	for i, v := range vals {
		out[i] = v.Description
	}
	return out
}

// ---------- Bash ----------

func generateBash(prog string, data completion.CompletionData) string {
	topLevel, subCmds := categorizeCommands(data.Commands)

	var b strings.Builder
	b.WriteString("# bash completion for " + prog + "\n")
	b.WriteString("# Generated by: " + prog + " completion bash\n\n")
	b.WriteString("_" + prog + "() {\n")
	b.WriteString("    local cur prev words cword\n")
	b.WriteString("    _init_completion -n : || return\n\n")

	// Detect current command
	b.WriteString("    local cmd=\"\"\n")
	b.WriteString("    for ((i=1; i < cword; i++)); do\n")
	b.WriteString("        if [[ \"${words[i]}\" != -* ]]; then\n")
	b.WriteString("            cmd=\"${words[i]}\"\n")
	b.WriteString("            break\n")
	b.WriteString("        fi\n")
	b.WriteString("    done\n\n")

	// Flag value completion (for flags that take a value)
	b.WriteString("    # Flag value completion\n")
	b.WriteString("    case \"$prev\" in\n")
	// Global flags
	for _, f := range data.Flags {
		if !isStandalone(f.Type) {
			if f.Long == "keyfile" {
				// keyfile is a file path
				if f.Long != "" {
					b.WriteString("        --" + f.Long + ") _filedir; return ;;\n")
				}
				if f.Short != "" {
					b.WriteString("        -" + f.Short + ") _filedir; return ;;\n")
				}
			} else if vals := flagValueDescriptions("", f.Long, data.FlagValues); len(vals) > 0 {
				valStr := strings.Join(vals, " ")
				if f.Long != "" {
					b.WriteString("        --" + f.Long + ") COMPREPLY=($(compgen -W \"" + valStr + "\" -- \"$cur\")); return ;;\n")
				}
				if f.Short != "" {
					b.WriteString("        -" + f.Short + ") COMPREPLY=($(compgen -W \"" + valStr + "\" -- \"$cur\")); return ;;\n")
				}
			} else {
				// Other value flags — just stop completion
				if f.Long != "" {
					b.WriteString("        --" + f.Long + ") return ;;\n")
				}
				if f.Short != "" {
					b.WriteString("        -" + f.Short + ") return ;;\n")
				}
			}
		}
	}
	// Command-specific value flags
	seen := make(map[string]bool)
	for _, cmd := range topLevel {
		for _, f := range flagsForCommand(cmd, data) {
			if !isStandalone(f.Type) {
				vals := flagValueDescriptions(cmd, f.Long, data.FlagValues)
				if f.Long != "" && !seen["--"+f.Long] {
					seen["--"+f.Long] = true
					if len(vals) > 0 {
						b.WriteString("        --" + f.Long + ") COMPREPLY=($(compgen -W \"" + strings.Join(vals, " ") + "\" -- \"$cur\")); return ;;\n")
					} else {
						b.WriteString("        --" + f.Long + ") return ;;\n")
					}
				}
				if f.Short != "" && !seen["-"+f.Short] {
					seen["-"+f.Short] = true
					if len(vals) > 0 {
						b.WriteString("        -" + f.Short + ") COMPREPLY=($(compgen -W \"" + strings.Join(vals, " ") + "\" -- \"$cur\")); return ;;\n")
					} else {
						b.WriteString("        -" + f.Short + ") return ;;\n")
					}
				}
			}
		}
	}
	b.WriteString("    esac\n\n")

	// Flag completion
	b.WriteString("    # Flag completion\n")
	b.WriteString("    if [[ \"$cur\" == -* ]]; then\n")
	// Global flags
	var globalFlags []string
	for _, f := range data.Flags {
		if f.Long != "" && f.Long != "help" {
			globalFlags = append(globalFlags, "--"+f.Long)
		}
		if f.Short != "" && f.Short != "h" {
			globalFlags = append(globalFlags, "-"+f.Short)
		}
	}
	b.WriteString("        local flags=\"" + strings.Join(globalFlags, " ") + "\"\n")
	b.WriteString("        case \"$cmd\" in\n")
	for _, cmd := range topLevel {
		flags := flagsForCommand(cmd, data)
		if len(flags) > 0 {
			var parts []string
			for _, f := range flags {
				if f.Long != "" {
					parts = append(parts, "--"+f.Long)
				}
				if f.Short != "" {
					parts = append(parts, "-"+f.Short)
				}
			}
			b.WriteString("            " + cmd + ") flags=\"$flags " + strings.Join(parts, " ") + "\" ;;\n")
		}
	}
	b.WriteString("        esac\n")
	b.WriteString("        COMPREPLY=($(compgen -W \"$flags\" -- \"$cur\"))\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n\n")

	// Command completion
	b.WriteString("    # Command completion\n")
	b.WriteString("    if [[ -z \"$cmd\" ]]; then\n")
	b.WriteString("        COMPREPLY=($(compgen -W \"" + strings.Join(topLevel, " ") + "\" -- \"$cur\"))\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n\n")

	// Subcommand + dynamic completion
	b.WriteString("    # Subcommand and positional completion\n")
	b.WriteString("    case \"$cmd\" in\n")
	for parent, subs := range subCmds {
		b.WriteString("        " + parent + ") COMPREPLY=($(compgen -W \"" + strings.Join(subs, " ") + "\" -- \"$cur\")); return ;;\n")
	}
	var secretCmds, folderCmds []string
	for _, cmd := range topLevel {
		if secretCommands[cmd] {
			secretCmds = append(secretCmds, cmd)
		}
		if folderCommands[cmd] {
			folderCmds = append(folderCmds, cmd)
		}
	}
	if len(secretCmds) > 0 {
		b.WriteString("        " + strings.Join(secretCmds, "|") + ")\n")
		b.WriteString("            COMPREPLY=($(compgen -W \"$(" + prog + " __complete secrets \"$cur\" 2>/dev/null)\" -- \"$cur\"))\n")
		b.WriteString("            ;;\n")
	}
	if len(folderCmds) > 0 {
		b.WriteString("        " + strings.Join(folderCmds, "|") + ")\n")
		b.WriteString("            COMPREPLY=($(compgen -W \"$(" + prog + " __complete folders \"$cur\" 2>/dev/null)\" -- \"$cur\"))\n")
		b.WriteString("            ;;\n")
	}
	b.WriteString("    esac\n")
	b.WriteString("}\n\n")
	b.WriteString("complete -o nospace -F _" + prog + " " + prog + "\n")

	return b.String()
}

// ---------- Zsh ----------

func generateZsh(prog string, data completion.CompletionData) string {
	topLevel, subCmds := categorizeCommands(data.Commands)

	var b strings.Builder
	b.WriteString("#compdef " + prog + "\n\n")
	b.WriteString("# zsh completion for " + prog + "\n")
	b.WriteString("# Generated by: " + prog + " completion zsh\n\n")

	// Dynamic completion helpers
	b.WriteString("_" + prog + "_secrets() {\n")
	b.WriteString("    local -a secrets\n")
	b.WriteString("    secrets=(${(f)\"$(" + prog + " __complete secrets \"$PREFIX\" 2>/dev/null)\"})\n")
	b.WriteString("    compadd -a secrets\n")
	b.WriteString("}\n\n")

	b.WriteString("_" + prog + "_folders() {\n")
	b.WriteString("    local -a folders\n")
	b.WriteString("    folders=(${(f)\"$(" + prog + " __complete folders \"$PREFIX\" 2>/dev/null)\"})\n")
	b.WriteString("    compadd -a folders\n")
	b.WriteString("}\n\n")

	// Collect global flag specs — included in every subcommand's _arguments
	// so that global flags (e.g. --keyfile) work regardless of position.
	var globalFlagSpecs []string
	var globalValueFlags []string
	for _, f := range data.Flags {
		if f.Long == "help" {
			continue
		}
		globalFlagSpecs = append(globalFlagSpecs, zshGlobalFlagSpec(f, data.FlagValues))
		if !isStandalone(f.Type) {
			if f.Short != "" {
				globalValueFlags = append(globalValueFlags, "-"+f.Short)
			}
			if f.Long != "" {
				globalValueFlags = append(globalValueFlags, "--"+f.Long)
			}
		}
	}

	// Main function — uses manual command detection instead of _arguments -C
	// to avoid failures when command-specific flags precede positional args
	// (e.g. "sympa show -c Root/<TAB>" would fail because _arguments -C at the
	// top level doesn't know about -c and refuses to enter the args state).
	b.WriteString("_" + prog + "() {\n")

	// Commands array with descriptions
	b.WriteString("    local -a commands\n")
	b.WriteString("    commands=(\n")
	for _, cmd := range topLevel {
		desc := zshEscape(data.CommandDescriptions[cmd])
		b.WriteString("        '" + cmd + ":" + desc + "'\n")
	}
	b.WriteString("    )\n\n")

	// Find the subcommand — first non-flag word after the program name.
	// Skip global value flags and their arguments.
	b.WriteString("    local cmd=''\n")
	b.WriteString("    local -i cmd_idx=0\n")
	b.WriteString("    local -i i\n")
	b.WriteString("    for (( i = 2; i < CURRENT; i++ )); do\n")
	b.WriteString("        case \"${words[i]}\" in\n")
	if len(globalValueFlags) > 0 {
		b.WriteString("            " + strings.Join(globalValueFlags, "|") + ") (( i++ )) ;;\n")
	}
	b.WriteString("            -*) ;;\n")
	b.WriteString("            *)\n")
	b.WriteString("                cmd=\"${words[i]}\"\n")
	b.WriteString("                cmd_idx=$i\n")
	b.WriteString("                break\n")
	b.WriteString("                ;;\n")
	b.WriteString("        esac\n")
	b.WriteString("    done\n\n")

	// No command yet — complete command names
	b.WriteString("    if [[ -z \"$cmd\" ]]; then\n")
	b.WriteString("        _describe 'commands' commands\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n\n")

	// Shift context so words[1] = subcommand name (matches _arguments expectations)
	b.WriteString("    (( CURRENT -= cmd_idx - 1 ))\n")
	b.WriteString("    shift $(( cmd_idx - 1 )) words\n\n")

	// Per-command completion
	b.WriteString("    case $cmd in\n")

	for _, cmd := range topLevel {
		flags := flagsForCommand(cmd, data)
		if subs, ok := subCmds[cmd]; ok {
			// Subcommand parent — describe subcommands
			b.WriteString("        " + cmd + ")\n")
			b.WriteString("            local -a subcmds\n")
			b.WriteString("            subcmds=(\n")
			for _, sub := range subs {
				fullPath := cmd + " " + sub
				desc := zshEscape(data.CommandDescriptions[fullPath])
				b.WriteString("                '" + sub + ":" + desc + "'\n")
			}
			b.WriteString("            )\n")
			b.WriteString("            _describe 'subcommands' subcmds\n")
			b.WriteString("            ;;\n")
		} else if secretCommands[cmd] {
			b.WriteString("        " + cmd + ")\n")
			b.WriteString("            _arguments \\\n")
			for _, spec := range globalFlagSpecs {
				b.WriteString("                " + spec + " \\\n")
			}
			for _, f := range flags {
				b.WriteString("                " + zshCmdFlagSpec(cmd, f, data.FlagValues) + " \\\n")
			}
			b.WriteString("                '1:secret:_" + prog + "_secrets'\n")
			b.WriteString("            ;;\n")
		} else if folderCommands[cmd] {
			b.WriteString("        " + cmd + ")\n")
			b.WriteString("            _arguments \\\n")
			for _, spec := range globalFlagSpecs {
				b.WriteString("                " + spec + " \\\n")
			}
			for _, f := range flags {
				b.WriteString("                " + zshCmdFlagSpec(cmd, f, data.FlagValues) + " \\\n")
			}
			b.WriteString("                '1:folder:_" + prog + "_folders'\n")
			b.WriteString("            ;;\n")
		} else if len(flags) > 0 || len(globalFlagSpecs) > 0 {
			b.WriteString("        " + cmd + ")\n")
			b.WriteString("            _arguments \\\n")
			for _, spec := range globalFlagSpecs {
				b.WriteString("                " + spec + " \\\n")
			}
			for _, f := range flags {
				b.WriteString("                " + zshCmdFlagSpec(cmd, f, data.FlagValues) + " \\\n")
			}
			b.WriteString("                '*:'\n")
			b.WriteString("            ;;\n")
		}
	}

	b.WriteString("    esac\n")
	b.WriteString("}\n\n")
	b.WriteString("_" + prog + " \"$@\"\n")

	return b.String()
}

// zshEscape escapes characters for zsh completion descriptions.
func zshEscape(s string) string {
	s = strings.ReplaceAll(s, "'", "'\\''")
	s = strings.ReplaceAll(s, "[", "\\[")
	s = strings.ReplaceAll(s, "]", "\\]")
	return s
}

// zshGlobalFlagSpec formats a global FlagPair (where Short/Long are normal).
func zshGlobalFlagSpec(f completion.FlagPair, fv map[string][]completion.CompletionValue) string {
	desc := zshEscape(f.Description)
	valueSpec := ""
	if !isStandalone(f.Type) {
		if f.Long == "keyfile" {
			valueSpec = ":file:_files"
		} else if vals := flagValueDescriptions("", f.Long, fv); len(vals) > 0 {
			valueSpec = ": :(" + strings.Join(vals, " ") + ")"
		} else {
			valueSpec = ": : "
		}
	}

	if f.Short != "" && f.Long != "" {
		return "'(-" + f.Short + " --" + f.Long + ")'{-" + f.Short + ",--" + f.Long + "}'[" + desc + "]" + valueSpec + "'"
	}
	if f.Long != "" {
		return "'--" + f.Long + "[" + desc + "]" + valueSpec + "'"
	}
	return "'-" + f.Short + "[" + desc + "]" + valueSpec + "'"
}

// zshCmdFlagSpec formats a command-level cmdFlag for zsh _arguments.
func zshCmdFlagSpec(cmd string, f cmdFlag, fv map[string][]completion.CompletionValue) string {
	desc := zshEscape(f.Desc)
	valueSpec := ""
	if !isStandalone(f.Type) {
		if vals := flagValueDescriptions(cmd, f.Long, fv); len(vals) > 0 {
			valueSpec = ": :(" + strings.Join(vals, " ") + ")"
		} else {
			valueSpec = ": : "
		}
	}

	if f.Short != "" && f.Long != "" {
		return "'(-" + f.Short + " --" + f.Long + ")'{-" + f.Short + ",--" + f.Long + "}'[" + desc + "]" + valueSpec + "'"
	}
	if f.Long != "" {
		return "'--" + f.Long + "[" + desc + "]" + valueSpec + "'"
	}
	return "'-" + f.Short + "[" + desc + "]" + valueSpec + "'"
}

// ---------- Fish ----------

func generateFish(prog string, data completion.CompletionData) string {
	topLevel, subCmds := categorizeCommands(data.Commands)

	var b strings.Builder
	b.WriteString("# fish completion for " + prog + "\n")
	b.WriteString("# Generated by: " + prog + " completion fish\n\n")

	// Clear any stale completions from a previous version.
	b.WriteString("complete -c " + prog + " -e\n\n")

	// Global flags
	b.WriteString("# Global flags\n")
	for _, f := range data.Flags {
		if f.Long == "help" {
			continue
		}
		b.WriteString(fishGlobalFlagLine(prog, f, data.FlagValues))
	}
	b.WriteString("\n")

	// Top-level commands
	b.WriteString("# Commands\n")
	for _, cmd := range topLevel {
		desc := fishEscape(data.CommandDescriptions[cmd])
		b.WriteString("complete -c " + prog + " -f -n '__fish_use_subcommand' -a '" + cmd + "' -d '" + desc + "'\n")
	}
	b.WriteString("\n")

	// Subcommands
	for parent, subs := range subCmds {
		b.WriteString("# " + parent + " subcommands\n")
		for _, sub := range subs {
			fullPath := parent + " " + sub
			desc := fishEscape(data.CommandDescriptions[fullPath])
			b.WriteString("complete -c " + prog + " -f -n '__fish_seen_subcommand_from " + parent + "' -a '" + sub + "' -d '" + desc + "'\n")
		}
	}
	b.WriteString("\n")

	// Command-specific flags
	b.WriteString("# Command-specific flags\n")
	for _, cmd := range topLevel {
		for _, f := range flagsForCommand(cmd, data) {
			b.WriteString(fishCmdFlagLine(prog, cmd, f, data.FlagValues))
		}
	}
	b.WriteString("\n")

	// Dynamic secret completion
	var secretCmds, folderCmds []string
	for _, cmd := range topLevel {
		if secretCommands[cmd] {
			secretCmds = append(secretCmds, cmd)
		}
		if folderCommands[cmd] {
			folderCmds = append(folderCmds, cmd)
		}
	}
	if len(secretCmds) > 0 {
		b.WriteString("# Dynamic secret path completion\n")
		b.WriteString("complete -c " + prog + " -f -n '__fish_seen_subcommand_from " + strings.Join(secretCmds, " ") + "' -a '(" + prog + " __complete secrets (commandline -ct) 2>/dev/null)'\n")
	}
	if len(folderCmds) > 0 {
		b.WriteString("# Dynamic folder path completion\n")
		b.WriteString("complete -c " + prog + " -f -n '__fish_seen_subcommand_from " + strings.Join(folderCmds, " ") + "' -a '(" + prog + " __complete folders (commandline -ct) 2>/dev/null)'\n")
	}

	return b.String()
}

// fishGlobalFlagLine generates a fish completion line for a global flag.
func fishGlobalFlagLine(prog string, f completion.FlagPair, fv map[string][]completion.CompletionValue) string {
	isFile := f.Long == "keyfile" || f.Type == completion.FlagTypeFile
	var parts []string
	if isFile {
		// Use -r -F (require arg + force file completion); -f would conflict with -F.
		parts = append(parts, "complete", "-c", prog)
	} else {
		parts = append(parts, "complete", "-c", prog, "-f")
	}
	if f.Long != "" {
		parts = append(parts, "-l", f.Long)
	}
	if f.Short != "" {
		parts = append(parts, "-s", f.Short)
	}
	if !isStandalone(f.Type) {
		parts = append(parts, "-r")
		if isFile {
			parts = append(parts, "-F")
		}
	}
	if vals := flagValueDescriptions("", f.Long, fv); len(vals) > 0 {
		parts = append(parts, "-a", "'"+strings.Join(vals, " ")+"'")
	}
	if f.Description != "" {
		parts = append(parts, "-d", "'"+fishEscape(f.Description)+"'")
	}
	return strings.Join(parts, " ") + "\n"
}

// fishCmdFlagLine generates a fish completion line for a command-specific flag.
func fishCmdFlagLine(prog, cmd string, f cmdFlag, fv map[string][]completion.CompletionValue) string {
	isFile := f.Type == completion.FlagTypeFile
	var parts []string
	if isFile {
		parts = append(parts, "complete", "-c", prog)
	} else {
		parts = append(parts, "complete", "-c", prog, "-f")
	}
	parts = append(parts, "-n", "'__fish_seen_subcommand_from "+cmd+"'")
	if f.Long != "" {
		parts = append(parts, "-l", f.Long)
	}
	if f.Short != "" {
		parts = append(parts, "-s", f.Short)
	}
	if !isStandalone(f.Type) {
		parts = append(parts, "-r")
		if isFile {
			parts = append(parts, "-F")
		}
	}
	if vals := flagValueDescriptions(cmd, f.Long, fv); len(vals) > 0 {
		parts = append(parts, "-a", "'"+strings.Join(vals, " ")+"'")
	}
	if f.Desc != "" {
		parts = append(parts, "-d", "'"+fishEscape(f.Desc)+"'")
	}
	return strings.Join(parts, " ") + "\n"
}

// fishEscape escapes single quotes for fish shell strings.
func fishEscape(s string) string {
	return strings.ReplaceAll(s, "'", "\\'")
}
